name: Tests

on:
    push:
    pull_request:

jobs:
    run_unit_test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: pip install numpy
            - run: python tests/unit_tests/test_my_utils.py

    run_func_test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: bash tests/functional_tests/test_print_fires.sh

    run_linter:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: mamba-org/setup-micromamba@v2
              with:
                environment-file: env.yml
                init-shell: bash
            - run: pycodestyle $(git ls-files '*.py')
              shell: bash -l {0}
